/**Controller principal que vai ser responsável por iniciar o programa
 *
 * @author Joel Henrique Silva Santos
 * 
 * @version 1.0
 * 
 */

package br.com.joel.view;

import br.com.joel.controlller.ControllerPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class TelaConversor extends javax.swing.JFrame {

    private ControllerPrincipal controllerPrincipal = new ControllerPrincipal();

    /**
     * Creates new form TelaConversor
     */
    public TelaConversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextoNormal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTextoCifrado = new javax.swing.JTextArea();
        lblChave = new javax.swing.JLabel();
        btnDecifrar = new javax.swing.JButton();
        btnCifrar = new javax.swing.JButton();
        lblTexto = new javax.swing.JLabel();
        lblTextoCifrado = new javax.swing.JLabel();
        txtChave = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(234, 234, 234));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTextoNormal.setColumns(20);
        txtTextoNormal.setRows(5);
        jScrollPane1.setViewportView(txtTextoNormal);

        pnlPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 599, 169));

        txtTextoCifrado.setColumns(20);
        txtTextoCifrado.setRows(5);
        jScrollPane2.setViewportView(txtTextoCifrado);

        pnlPrincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, 599, 169));

        lblChave.setText("Chave:");
        pnlPrincipal.add(lblChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 431, 41, 29));

        btnDecifrar.setText("Decifrar");
        btnDecifrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDecifrarMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnDecifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 431, -1, 29));

        btnCifrar.setText("Cifrar");
        btnCifrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCifrarMouseClicked(evt);
            }
        });
        pnlPrincipal.add(btnCifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 431, -1, 29));

        lblTexto.setText("Texto:");
        pnlPrincipal.add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 23));

        lblTextoCifrado.setText("Texto Cifrado:");
        pnlPrincipal.add(lblTextoCifrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, -1, 23));

        txtChave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26" }));
        pnlPrincipal.add(txtChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCifrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCifrarMouseClicked

        try {

            if (Integer.parseInt(this.txtChave.getItemAt(this.txtChave.getSelectedIndex())) < 1 || Integer.parseInt(this.txtChave.getItemAt(this.txtChave.getSelectedIndex())) > 26) {
                throw new NumberFormatException();
            } else if (this.txtTextoNormal.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite o texto no campo texto normal para cifrar");
            } else {
                String textoCifrado = controllerPrincipal.funcaoCifra(this.txtTextoNormal.getText(), Integer.parseInt(this.txtChave.getItemAt(this.txtChave.getSelectedIndex())));
                this.txtTextoCifrado.setText(textoCifrado);
                this.txtTextoNormal.setText("");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Digite um numero valido para chave entre 1 até 26");
        }

    }//GEN-LAST:event_btnCifrarMouseClicked

    private void btnDecifrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDecifrarMouseClicked

        try {

            if (Integer.parseInt(this.txtChave.getItemAt(this.txtChave.getSelectedIndex())) < 1 || Integer.parseInt(this.txtChave.getItemAt(this.txtChave.getSelectedIndex())) > 26) {
                throw new NumberFormatException();
            } else if (this.txtTextoCifrado.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite o texto no campo texto cifrado para decifrar");
            } else {
                String textoNormal = controllerPrincipal.funcaoDecifra(this.txtTextoCifrado.getText(), Integer.parseInt(this.txtChave.getItemAt(this.txtChave.getSelectedIndex())));
                this.txtTextoNormal.setText(textoNormal);
                this.txtTextoCifrado.setText("");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Digite um numero valido para chave entre 1 até 26");
        }

    }//GEN-LAST:event_btnDecifrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCifrar;
    private javax.swing.JButton btnDecifrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblChave;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTextoCifrado;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JComboBox<String> txtChave;
    private javax.swing.JTextArea txtTextoCifrado;
    private javax.swing.JTextArea txtTextoNormal;
    // End of variables declaration//GEN-END:variables

}
